MODEL:
  MODEL_TYPE: UNet

  MODEL_CONFIG:
    n_channels: 3
    n_classes: 1
    bilinear: True
    feature_scale: 4
    is_deconv: True
    is_batchnorm: True

  PRETRAIN_CKPT: True

SEED: 1234

DATASET:
  DATASET_LOADER: BRATSDataset
  DATASET_CONFIG:
    base_path: "D:/Projects/Brats_Dataset_Png"
    # base_path: "/Users/srikeshnagoji/Documents/PythonWorkSpace/jupyter_lab_workspace/PES/final_thesis/dataset/ISIC_skin_converted"
    subset_count: -1

  # DATASET_LOADER: BrainMRIDataset
  # DATASET_CONFIG:
  #   base_path: E:/Projects/Data-Science/MTech/Courses/16.Capstone-Projects/Data/kaggle_3m
  #   subset_count: -1

  DATASET_TRANSFORMS:
    DATASET_TRANSFORM_NAME: Default
    DATASET_TRANSFORM_CONFIG:
      image_size: 128

WANDB:
  LOG_STEP_INTERVAL: 10
  SAVE_OUTPUT_EPOCH_INTERVAL: 5

TRAIN:
  OUTPUT_DIR: "output"
  MAX_EPOCHS: 30
  BASE_LR: 0.05
  BATCH_SIZE: 16
  #20

  DETERMINISTIC: True
  N_GPU: 1
  USE_CHECKPOINT: False

  TRAIN_VAL_SPLIT: 0.1

  SAVE_INTERVAL: 1

  LOSS_NAME: DiceCEMixLoss

  # OPTIM_PACKAGE: lion_pytorch
  # OPTIM_NAME: Lion
  # OPTIM_CONFIG:
  #   lr: 0.0001
  #   betas: [0.95, 0.999]
  #   weight_decay: 0.000001

  # Sam's Using SGD..
  OPTIM_PACKAGE: torch.optim
  OPTIM_NAME: SGD
  OPTIM_CONFIG:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

  ACCELERATOR_CONFIG:
    REPORT_TO: wandb
    GRADIENT_ACCUMULATION_STEPS: 4
    MIXED_PRECISION: 'no'


TEST:
  # OUTPUT_DIR: "test_log\\swin_tiny_patch4_window7_224_ep300"
  # LOG_OUTPUT_DIR: "test_log\\swin_tiny_patch4_window7_224_ep300\\log"

  TRAIN_TEST_SPLIT: 0.12
  LOAD_CKPT: "best" # OR "cur"

  DETERMINISTIC: True
  N_GPU: 1
  IS_SAVENII: True


  ACCELERATOR_CONFIG:
    REPORT_TO: wandb
    GRADIENT_ACCUMULATION_STEPS: 4
    MIXED_PRECISION: 'no'